version: '3.8'
services:
  app:
    build: .
    command: yarn start
    ports:
      - 8080:8080
    volumes:
#      - ./downloads:/app/downloads/
      - .:/app
      - trick:/app/node_modules

    environment:
      - PORT=8080
volumes:
  trick:
